/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#00174b",
        "surface-container-low": "#eff4ff",
        "primary-fixed": "#dbe1ff",
        "secondary-fixed-dim": "#4edea3",
        "primary": "#004ac6",
        "surface-bright": "#f8f9ff",
        "secondary-fixed": "#6ffbbe",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#eaf1ff",
        "surface-container-high": "#dce9ff",
        "on-background": "#0b1c30",
        "on-tertiary": "#ffffff",
        "secondary-container": "#6cf8bb",
        "inverse-surface": "#213145",
        "on-secondary-container": "#00714d",
        "background": "#f8f9ff",
        "error-container": "#ffdad6",
        "on-surface": "#0b1c30",
        "tertiary": "#784b00",
        "primary-fixed-dim": "#b4c5ff",
        "on-primary-fixed-variant": "#003ea8",
        "tertiary-fixed-dim": "#ffb95f",
        "on-secondary": "#ffffff",
        "secondary": "#006c49",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#996100",
        "outline": "#737686",
        "on-primary-container": "#eeefff",
        "error": "#ba1a1a",
        "surface": "#f8f9ff",
        "surface-tint": "#0053db",
        "on-surface-variant": "#434655",
        "on-secondary-fixed": "#002113",
        "surface-container": "#e5eeff",
        "surface-dim": "#cbdbf5",
        "outline-variant": "#c3c6d7",
        "on-tertiary-fixed": "#2a1700",
        "on-error": "#ffffff",
        "tertiary-fixed": "#ffddb8",
        "on-secondary-fixed-variant": "#005236",
        "surface-variant": "#d3e4fe",
        "on-tertiary-container": "#ffeedd",
        "surface-container-highest": "#d3e4fe",
        "on-tertiary-fixed-variant": "#653e00",
        "inverse-primary": "#b4c5ff",
        "on-primary": "#ffffff",
        "primary-container": "#2563eb",
        // Additional Microsoft Teams theme tokens for Calendar
        teams: {
          brand: '#5b5fc7',
          brandDark: '#4f52b2',
          brandLight: '#ebeaf9',
          brandPill: '#e0e0f5',
          grayBg: '#f8f9fa',
          border: '#e5e7eb',
          textPrimary: '#242424',
          textSecondary: '#616161',
          eventBg: '#e8eafb',
          eventBorder: '#5b5fc7',
          timeLine: '#5b5fc7'
        }
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "pill": "9999px"
      },
      spacing: {
        gutter: "1.5rem",
        margin: "2rem",
        "space-lg": "1.5rem",
        "space-2xs": "0.25rem",
        "space-2xl": "3rem",
        "space-sm": "0.75rem",
        "space-xs": "0.5rem",
        "space-md": "1rem",
        "space-xl": "2rem",
        "margin-mobile": "1rem",
        "gutter-mobile": "1rem",
      },
      fontFamily: {
        "title-sm": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        caption: ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "title-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        sans: ["Plus Jakarta Sans", "Inter", "sans-serif"],
        inter: ["Inter", "sans-serif"]
      },
      fontSize: {
        "title-sm": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "display-lg-mobile": ["26px", { lineHeight: "34px", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        caption: ["11px", { lineHeight: "14px", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "title-md": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "display-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-lg": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-md": ["13px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-sm": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
      }
    },
  },
  plugins: [],
};
